# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
    </filter>

        <match **>
      @type elasticsearch
      host elasticsearch.logging.svc.cluster.local
      port 9200
      logstash_format true
      logstash_prefix kubernetes-logs
      include_tag_key true
    </match>
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"fluent.conf":"\u003csource\u003e\n  @type tail\n  path /var/log/containers/*.log\n  pos_file /var/log/fluentd-containers.log.pos\n  tag kubernetes.*\n  read_from_head true\n  \u003cparse\u003e\n    @type json\n    time_key time\n    time_format %Y-%m-%dT%H:%M:%S.%NZ\n  \u003c/parse\u003e\n\u003c/source\u003e\n\n\u003cfilter kubernetes.**\u003e\n  @type kubernetes_metadata\n  @id filter_kube_metadata\n\u003c/filter\u003e\n\n\u003cmatch **\u003e\n  @type elasticsearch\n  host elasticsearch.logging.svc.cluster.local\n  port 9200\n  logstash_format true\n  logstash_prefix kubernetes-logs\n  include_tag_key true\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"fluentd-config","namespace":"logging"}}
  creationTimestamp: "2026-02-27T07:55:06Z"
  name: fluentd-config
  namespace: logging
  resourceVersion: "4836"
  uid: 6b65357e-e20f-43e8-9e77-598636a330aa
